---
title: "Introduction"
format: html
---

### History

The development of the Czech Vegetation Database (formerly Czech National Phytosociological Database) was stimulated by the activities of the [European Vegetation Survey](https://euroveg.org/) Working Group of the [International Association for Vegetation Science](https://www.iavs.org/), which was founded in 1992. One of the aims of this group was to support national vegetation survey programs in European countries ([Mucina et al. 1993](https://doi.org/10.2307/3235603)). The creation of the national vegetation databases was a key activity towards this aim. To support database development, Stephan Hennekens developed the database management program Turboveg and provided it to various vegetation researchers and research groups in Europe (Schaminée & Hennekens 1995).

John Rodwell from Lancaster University, UK, received funding for the project “Safeguarding the Biodiversity of Eastern Europe” (1995–1998) from the Darwin Initiative of the British Government. The aim of this project was to train vegetation scientists from five central and eastern European countries, including the Czech Republic, in modern methods of vegetation survey, including the management of vegetation databases. The Czech participants included Milan Chytrý as a coordinator and Martin Duchoslav, Handrij Härtel, Tomáš Kučera, Kateřina Šumberová and Lubomír Tichý as team members. In close collaboration with Stephan Hennekens, Turboveg was prepared for use in the Czech Republic, which required compiling standard species lists and initial versions of the databases for bibliographic references and authors of plot records.

Thanks to this training and further support from John Rodwell and Stephan Hennekens, as well as cooperation on the development of the common Austrian-Czech-Slovak species list with Harald Niklfeld, Walter Gutermann, Ladislav Mucina, Ivan Jarolímek and Milan Valachovič, the Czech National Phytosociological Database was founded by Milan Chytrý at Masaryk University in 1996 ([Chytrý 1996](https://www.sci.muni.cz/botany/chytry/Chytry1996_Zpravy-CBS.pdf), [1997](https://www.sci.muni.cz/botany/chytry/Chytry1997_Zpravy-CBS-Mater.pdf)). The training course on vegetation databanking using Turboveg for Czechia and Slovakia took place in Brno in February 1997, organized by Milan Chytrý, John Rodwell, and his database assistant Julian Dring. This course, attended by 42 participants from Czechia nad 8 from Slovakia, helped develop an organizational structure for the national vegetation database, with a central database at Masaryk University in Brno, managed by Milan Chytrý, and a network of local collaborators in other important botanical institutions across the country, most notably the Institute of Botany of the Czech Academy of Sciences, Charles University in Prague, Palacký University in Olomouc, University of South Bohemia in České Budějovice, and the Czech University of Life Sciences in Prague.

Thanks to the collective effort of several collaborators, the database grew rapidly by harmonizing the already existing data in various electronic formats and digitizing data from the literature and field notebooks. In October 1997, the database contained 6408 vegetation plots ([Chytrý 1997](https://www.sci.muni.cz/botany/chytry/Chytry1997_Zpravy-CBS-Mater.pdf)). From 1999, Marie Rafajová was appointed as a full-time data manager on a Czech Science Foundation project obtained by M. Chytrý. This enabled the massive digitization of data, resulting in 55,310 vegetation plots being digitized by November 2002 ([Chytrý & Rafajová 2003](http://www.sci.muni.cz/botany/chytry/Pre2003.pdf)). Marie Rafajová left the team in 2003, being successively replaced by Ilona Knollová (Kuželová), Zdenka Preislerová (Otýpková), Dana Holubová (Michalcová) and again Ilona Knollová. Further plots were obtained through a series of Czech Science Foundation projects that supported the preparation of the monograph Vegetation of the Czech Republic ([Chytrý 2007–2013](https://botzool.cz/vegsci/vegetationCR)). These plots were provided by project collaborators or digitized from older literature, nature conservation reports and field notebooks. By May 2012, the database contained 99,586 vegetation plots ([Chytrý & Michalcová 2012](http://www.biodiversity-plants.de/biodivers_ecol/publishing/b-e.00136.pdf)).

In 2011, the Czech National Phytosociological Database was indexed in the Global Index of Vegetation-Plot Databases (GIVD, Dengler et al. 2011) with the code EU-CZ-001. In 2012, it became one of the founding members of the European Vegetation Archive, an integrated database of European vegetation plots (Chytrý et al., 2016). In 2013, it joined sPlot, the Global Vegetation Database (Bruelheide et al., 2019). Through these partnerships, Czech vegetation data contributed to numerous synthetic studies of vegetation on the European and global scales. Moreover, the species occurrence records from the database were imported into the Pladias – Database of the Czech Flora and Vegetation, which was launched in an online version in 2018 and integrated plant species distribution records from multiple sources (Wild et al. 2019, Chytrý et al. 2021).

### References

Chytrý M. & Rafajová M. (2003): Czech National Phytosociological Database: basic statistics of the available vegetation-plot data. Preslia 75: 1–15. [\[pdf\]](http://www.sci.muni.cz/botany/chytry/Pre2003.pdf)
