---
title: "Data availability"
format: html
---

Data from the Czech National Phytosociological Database (CNPD) are available directly from CNPD (for analyses at the national scale), from [EVA](http://euroveg.org/eva-database) (for analyses at the international scale within Europe) and from [sPlot](https://www.idiv.de/en/splot.html) (for global analyses). Species occurrence data are available in the Pladias database. There are three regimes of data availability:

-   Public data freely available [online](https://botzool.cz/vegsci/phytosociologicalDb-fytoonline).

-   Data available upon request from database managers for academic research or applications in nature conservation, but not for commercial purposes. Data requests should be sent by e-mail to Ilona Knollová (📧 [ikuzel\@sci.muni.cz](mailto:ikuzel@sci.muni.cz)) or Milan Chytrý (📧 [chytry\@sci.muni.cz](mailto:chytry@sci.muni.cz)) with a description of the intended use of the data and criteria of data selection (e.g. area, vegetation type and time interval) and the required format.

-   Non-public data, which are stored in the central database but not made available to the public, or made available only for specific purposes specified by the data provider.

**Data use in publications should be acknowledged** **using the standard database citation**:\
Chytrý M. & Rafajová M. (2003): Czech National Phytosociological database: basic statistics of the available vegetation-plot data. Preslia 75: 1–15.

The papers where the data were published or authors of unpublished data should also be cited. These citations can be omitted if a data set from many different sources is used, in which no source is notably prevailing, and if the type of publication does not allow citing all the sources.
