---
title: "Data description"
format: html
---

**Data description**

Following the structure of the Turboveg database management software, vegetation-plot data in the Czech Vegetation Database are divided into three parts:

1.  Species data
2.  Header data
3.  Remarks

### 1. Species data

Species data contain unique plot identifiers (RELEVE_NR), species numbers (SPECIES_NR), cover-abundance grade for each species record (COVER_CODE), and vegetation layer for each species record (LAYER). Species numbers are linked to species names, and cover-abundances are linked to percentage covers using translation tables.

### 2. Header data

Header data contain information related to vegetation plots other than information on species and their cover-abundances. They include details of sampling methods, location, vegetation structure, vegetation type, and environmental information.

In addition to basic variables, the database also contains variables with outdated content (replaced by new variables with up-to-date content), variables that are rarely or never used, and one variable with non-unified content. Individual private databases that have been incorporated into the Czech Vegetation Database may also have contained other variables that are specific to those databases.

#### 2.1. Basic header-data variables

**Relevé number (RELEVE_NR).** Unique numerical code of the vegetation plot in the database.

**Country code (COUNTRY).** Two-letter country code according to ISO 3166-1 alpha-2. All plots recorded within the territory of the Czech Republic have the value “CZ”.

**Biblioreference (REFERENCE).** Bibliographic reference for vegetation plots that have been published in a citable source (article, book, student thesis, research report). A database of biblioreferences is available here: <https://www.sci.muni.cz/botany/tvref/>.

**Number of table in publication (TABLE_NR).** Number of the table in which the vegetation plot was published in the cited source. If the plot was separately rather than included in a table, the page number is given after the abbreviation “p.” (e.g., “p. 15”).

**Number of relevé in table (NR_IN_TAB).** Number of the vegetation plot in the cited source.

**Cover-abundance scale (COVER SCALE).** Species cover was recorded in vegetation plots either as percentages or using various scales derived from percentage cover intervals. Some scales are supplemented, for species with low cover, by grades expressing the number of individuals. The database contains both general scales used by multiple researchers and scales defined for a single purpose. In the database, grades of all scales are converted to the midpoint of the percentage interval they represent. General scales and their conversions to percentages are as follows (unused codes refer to scales defined only for a single purpose):

-   00 – Percentage (%)
-   01 – Braun-Blanquet (old), with seven grades: r = 1%, + = 2%, 1 = 3%, 2 = 13%, 3 = 38%, 4 = 63%, 5 = 88%
-   02 – Braun-Blanquet (new), with nine grades: r = 1%, + = 2%, 1 = 3%, 2m = 4%, 2a = 8%, 2b = 18%, 3 = 38%, 4 = 63%, 5 = 88%
-   03 – Londo: r1 = 1%, p1 = 1%, a1 = 1%, m1 = 1%, r2 = 2%, p2 = 2%, a2 = 2%, m2 = 2%, r4 = 4%, p4 = 4%, a4 = 4%, m4 = 4%, 1- = 7%, 1 = 10%, 1+ = 12%, 2- = 17%, 2 = 20%, 2+ = 22%, 3- = 27%, 3 = 30%, 3+ = 32%, 4- = 37%, 4 = 40%, 4+ = 42%, 5- = 47%, 5 = 50%, 5+ = 52%, 6- = 57%, 6 = 60%, 6+ = 62%, 7- = 67%, 7 = 70%, 7+ = 72%, 8- = 77%, 8 = 80%, 8+ = 82%, 9- = 87%, 9 = 90%, 9+ = 92%, 10 = 97%
-   04 – Presence/Absence: x, 1
-   05 – Ordinal scale (1–9), corresponding to the “Braun-Blanquet (new)” scale, but with mixed character-numeric symbols replaced by integers: 1 = 1%, 2 = 2%, 3 = 3%, 4 = 4%, 5 = 8%, 6 = 18%, 7 = 38%, 8 = 68%, 9 = 88%
-   06 – Barkman, Doing & Segal: r = 1%, +r = 1%, +p = 1%, +a = 1%, +b = 2%, 1p = 1%, 1a = 2%, 1b = 3%, 2m = 4%, 2a = 8%, 2b = 18%, 3a = 31%, 3b = 43%, 4a = 56%, 4b = 68%, 5a = 81%, 5b = 93%
-   07 – Doing: r = 1%, p = 1%, a = 2%, m = 4%, 1 = 10%, 2 = 20%, 3 = 30%, 4 = 40%, 5 = 50%, 6 = 60%, 7 = 70%, 8 = 80%, 9 = 90%, 10 = 97%
-   08 – Domin: + = 1%, 1 = 2%, 2 = 3%, 3 = 4%, 4 = 13%, 5 = 23%, 6 = 29%, 7 = 42%, 8 = 63%, 9 = 88%, 10 = 99%
-   10 – Zlatník: - = 1%, + = 2%, 1 = 3%, -2 = 10%, +2 = 20%, -3 = 31%, +3 = 44%, -4 = 56%, +4 = 69%, -5 = 81%, +5 = 94%
-   14 – Domin-Hadač: + = 0.5%, 1 = 1%, 2 = 2%, 3 = 4%, 4 = 10%, 5 = 20%, 6 = 29%, 7 = 42%, 8 = 63%, 9 = 85%, 10 = 98%
-   15 – Percentual (r, +): r = 0.1%, + = 0.5%, and integer values corresponding to percentages
-   18 – Hult-Sernader-DuRietz: r = 0.1%, + = 0.5%, 1 = 3.5%, 2 = 8.3%, 3 = 18.3%, 4 = 37.5%, 5 = 62.5%, 6 = 87.5

**Author code (AUTHOR).** Code of the author of the vegetation plot.

**Date (DATE).** Date of vegetation plot sampling, recorded in the format YYYYMMDD.

**Syntaxon (SYNTAXON).** Vegetation unit (syntaxon) to which the vegetation plot was subjectively assigned by its author or a database administrator, according to the classification system in the publication:

-   Chytrý M. (ed.) (2007–2013): Vegetace České republiky 1–4. Vegetation of the Czech Republic 1–4. Academia, Praha.

**ESy code (ESY_CODE).** Code of the vegetation unit according to the Vegetation of the Czech Republic (Chytrý 2007–2013), assigned based on vegetation classification by the expert system CzechVeg-Esy, version v1-2020-01-12 (<https://doi.org/10.5281/zenodo.3605562>). This field is empty for plots that were not unambiguously classified by the expert system.

**ESy name (ESY_NAME).** Name of the vegetation unit according to the Vegetation of the Czech Republic (Chytrý 2007–2013), assigned based on vegetation classification by the expert system CzechVeg-Esy, version v1-2020-01-12 (<https://doi.org/10.5281/zenodo.3605562>). This field is empty for plots that were not unambiguously classified by the expert system.

**Syntaxon code (ESY_K_CODE).** Code of the vegetation unit according to the expert system (taken from the ESy code variable), which is supplemented by subjective classification from the Syntaxon field for plots not classified by the expert system .

**Syntaxon name (ESY_K_NAME).** Name of the vegetation unit according to the expert system (taken from the ESy code variable), which is supplemented by subjective classification from the Syntaxon field for plots not classified by the expert system.

**Relevé area (SURF_AREA).** Area of the vegetation plot in m². A value of -1 represents missing data.

**Altitude (ALTITUDE).** Altitude of the vegetation plot in meters. A value of -1 represents missing data.

**Aspect (EXPOSITION).** Slope aspect in azimuth degrees from 1 to 360°.

**Slope (INCLINATIO).** Slope inclination in degrees. A value of -1 represents missing data.

**Cover total (COV_TOTAL).** Total percentage cover of all vegetation layers. A value of -1 represents missing data.

**Cover tree layer (COV_TREES).** Percentage cover of the tree layer. A value of -1 represents missing data.

**Cover shrub layer (COV_SHRUBS).** Percentage cover of the shrub layer. A value of -1 represents missing data.

**Cover herb layer (COV_HERBS).** Percentage cover of the herb layer. A value of -1 represents missing data.

**Cover moss layer (COV_MOSSES).** Percentage cover of the moss layer, including bryophytes and lichens. A value of -1 represents missing data.

**Height (high) tree layer (TREE_HIGH).** Height of the tree layer in meters. If the height of the higher and lower sublayers was estimated separately, this field contains the height of the higher sublayer.

**Height (high) shrub layer (SHRUB_HIGH).** Height of the shrub layer in meters. If the height of the higher and lower sublayers was estimated separately, this field contains the height of the higher sublayer.

**Height (high) herb layer (HERB_HIGH).** Height of the herb layer in centimeters. If the height of the higher and lower sublayers was estimated separately, this field contains the height of the higher sublayer.

**Maximum height herb layer (HERB_MAX).** Height of the tallest herbs exceeding the general herb layer level, in centimeters.

**Mosses identified (MOSS_IDENT).** Information on whether bryophytes were recorded and identified in the vegetation plot.

**Lichens identified (LICH_IDENT).** Information on whether lichens were recorded and identified in the vegetation plot.

**Coordinate source (COORD_CODE).** Method used to determine the coordinates of the vegetation plot, either in the field using a GPS receiver or subsequently using electronic or paper maps.

-   01 – GPS
-   02 – Geobáze 100 (electronic map 1 : 100,000)
-   03 – Geobáze 50 (electronic map 1 : 50,000)
-   04 – Vojenské mapy 50 (paper maps 1 : 50,000)
-   05 – ZM 5 (paper maps 1 : 5,000)
-   06 – ZM 10 (paper maps 1 : 10,000)
-   07 – ZM 25 (paper maps 1 : 25,000)
-   08 – ZM 50 (paper maps 1 : 50,000)
-   09 – GIS (electronic map)
-   10 – Military maps 25 (paper maps 1 : 25,000)
-   11 – www.mapy.cz (electronic map or orthophoto)
-   12 – www.atlas.cz (electronic map or orthophoto)
-   13 – Google Earth (orthophoto)

**Locality (LOCALITY).** Verbal description of the locality of the vegetation plot.

**Longitude (LONGITUDE).** Longitude in the format DDMMSS.SS in the WGS-84 system (e.g., 170322.55 corresponds to 17° 3’ 22.55’’ E).

**Latitude (LATITUDE).** Latitude in the format DDMMSS.SS in the WGS-84 system (e.g., 492215.12 corresponds to 49° 22’ 15.12’’ N).

**Precision (PRECISION).** Estimated uncertainty of the given geographic coordinates in meters.

**Bias GPS (BIAS_GPS).** Uncertainty of geographic coordinates measured using GPS, in meters.

**Field number (FIELD_NR).** Field number or code of the vegetation plot used by its author.

**Habitat (HABITAT).** Textual description of the abiotic or biotic environment in the vegetation plot and its close surroundings.

**Geology (GEOLOGY).** Textual description of geological bedrock in the vegetation plot.

**Soil (SOIL).** Textual description of soil in the vegetation plot.

#### 2.2. Header-data variables with outdated content replaced by new variables

**Syntaxon old (SYNTAX_OLD).** Vegetation unit (syntaxon) to which the vegetation plot was subjectively assigned by its author or database administrator according to the outdated classification system in the publication:

-   Moravec J., Balátová-Tuláčková E., Blažková D., Hadač E., Hejný S., Husák Š., Jeník J., Kolbek J., Krahulec F., Kropáč Z., Neuhäusl R., Rybníček K., Řehořek V. & Vicherek J. (1995): Rostlinná společenstva České republiky a jejich ohrožení. Ed. 2. Severočeskou přírodou, Příloha 1995: 1–206.

**Bias min (BIAS_MIN).** Estimated uncertainty of the given geographic coordinates in minutes. The first digit indicates uncertainty in minutes of longitude, and the second digit indicates uncertainty in minutes of latitude.

#### 2.3. Rarely or never used header-data variables

**UTM grid system code (UTM).** Code of geographic position in the Universal Transverse Mercator (UTM) system.

**Cover lichen layer (COV_LICHEN).** Percentage cover of lichens. Usually left empty, as lichens are included in the moss layer.

**Cover algae layer (COV_ALGAE).** Percentage cover of algae. A value of -1 represents missing data.

**Cover litter layer (COV_LITTER).** Percentage cover of litter (dead plant material). A value of -1 represents missing data.

**Cover open water (COV_WATER).** Percentage cover of open water surface. A value of -1 represents missing data.

**Cover bare rock (COV_ROCK).** Percentage cover of rock outcrops and stones. A value of -1 represents missing data.

**Height low tree layer (TREE_LOW).** Height of the lower tree sublayer in meters.

**Height low shrub layer (SHRUB_LOW).** Height of the lower shrub sublayer in meters.

**Height low herb layer (HERB_LOW).** Height of the lower herb sublayer in centimeters.

**Maximum height cryptogam layer (CRYPT_HIGH).** Height of the tallest bryophytes or lichens in centimeters.

**CEBA grid (CEBA_GRID).** Localization of the vegetation plot in the grid used for Central European flora mapping (see <https://pladias.cz/download/phytogeography>), either into basic grid cells (CEBA, Central European Basic Area) of size 10’ × 6’ minutes (e.g. 6062) or quadrants of these basic grid cells of size 5’ × 3’ minutes (e.g. 6062c).

#### 2.4. Inconsistently used header data variables with non-unified content

**Project code (PROJECT).** Project codes were entered by some data contributors and served their internal purposes. Within the entire Czech Vegetation Database, project codes are not unified. Consequently, the same project code used by different data contributors can refer to different projects.

### 3. Remarks

The REMARKS field contains non-standardized textual comments, such as details of taxonomic interpretation of some taxa reported in the plot, the uncertainty level of identification of specific taxa, and sampling methods. There is one REMARKS field for each plot.
